# Generated by Django 2.1 on 2018-08-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
