# Generated by Django 2.1 on 2018-08-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180821_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='linkes', max_length=40),
            preserve_default=False,
        ),
    ]
